export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

export const LOAD_POKEMON = "LOAD_POKEMON";
export const LIKED_POKEMON = "LIKED_POKEMON";
export const DISLIKED_POKEMON = "DISLIKED_POKEMON";
